### ISSUE TITLE
Deprecated Channels

### ISSUE THREAD

**Issue by anthonylavado** [jellyfin-archive/emby-plugin-channels#5]
Looking through to make a list of what channels can be deprecated/removed. For example, Revision3 is no longer in operation, and the website has been offline since March 31st 2017.

Since this is an older fork of this plug-in, some of this stuff has crept in, so let's remove what's no longer working/valid.

List for removal (to be edited as needed):
- [ ] Revision3

**Comment by hawken93** [comment]
That's sad because Rev3 is the first plugin that actually compiles for me..
But that's how it works.. :p

**Comment by anthonylavado** [comment]
Soundcloud is not issuing any API keys, so perhaps they should be removed too?

See: http://soundcloud.com/you/apps/new

**Comment by hawken93** [comment]
I'm just going to leave the keys in

**Comment by anthonylavado** [comment]
@hawken93 - Fine by me for now.
